controller_list:
  - name: fake_arm_left_controller
    type: $(arg fake_execution_type)
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: fake_arm_right_controller
    type: $(arg fake_execution_type)
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
initial:  # Define initial robot poses per group
  - group: arm_left
    pose: home_left
  - group: arm_right
    pose: home_right