// Generated by gencpp from file baxter_interface_msgs/EndpointTargets.msg
// DO NOT EDIT!


#ifndef BAXTER_INTERFACE_MSGS_MESSAGE_ENDPOINTTARGETS_H
#define BAXTER_INTERFACE_MSGS_MESSAGE_ENDPOINTTARGETS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <baxter_interface_msgs/EndpointTarget.h>

namespace baxter_interface_msgs
{
template <class ContainerAllocator>
struct EndpointTargets_
{
  typedef EndpointTargets_<ContainerAllocator> Type;

  EndpointTargets_()
    : limbs()
    , targets()  {
    }
  EndpointTargets_(const ContainerAllocator& _alloc)
    : limbs(_alloc)
    , targets(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _limbs_type;
  _limbs_type limbs;

   typedef std::vector< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >> _targets_type;
  _targets_type targets;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LIMB_L)
  #undef LIMB_L
#endif
#if defined(_WIN32) && defined(LIMB_R)
  #undef LIMB_R
#endif

  enum {
    LIMB_L = 1u,
    LIMB_R = 2u,
  };


  typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> const> ConstPtr;

}; // struct EndpointTargets_

typedef ::baxter_interface_msgs::EndpointTargets_<std::allocator<void> > EndpointTargets;

typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTargets > EndpointTargetsPtr;
typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTargets const> EndpointTargetsConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator1> & lhs, const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator2> & rhs)
{
  return lhs.limbs == rhs.limbs &&
    lhs.targets == rhs.targets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator1> & lhs, const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baxter_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a93e97384da9d755e296d234311cbcd";
  }

  static const char* value(const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a93e97384da9d75ULL;
  static const uint64_t static_value2 = 0x5e296d234311cbcdULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_interface_msgs/EndpointTargets";
  }

  static const char* value(const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "##limbs being controlled\n"
"uint8[] limbs\n"
"uint8 LIMB_L = 1\n"
"uint8 LIMB_R = 2\n"
"\n"
"##limb endpoint targets\n"
"EndpointTarget[] targets\n"
"================================================================================\n"
"MSG: baxter_interface_msgs/EndpointTarget\n"
"##limb pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"## motion mode\n"
"uint8 mode\n"
"uint8 MODE_CARTESIAN = 1\n"
"uint8 MODE_NORMAL = 2\n"
"uint8 MODE_SKIP = 3\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limbs);
      stream.next(m.targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndpointTargets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_interface_msgs::EndpointTargets_<ContainerAllocator>& v)
  {
    s << indent << "limbs[]" << std::endl;
    for (size_t i = 0; i < v.limbs.size(); ++i)
    {
      s << indent << "  limbs[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.limbs[i]);
    }
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >::stream(s, indent + "    ", v.targets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_INTERFACE_MSGS_MESSAGE_ENDPOINTTARGETS_H
