// Generated by gencpp from file baxter_interface_msgs/EndpointTarget.msg
// DO NOT EDIT!


#ifndef BAXTER_INTERFACE_MSGS_MESSAGE_ENDPOINTTARGET_H
#define BAXTER_INTERFACE_MSGS_MESSAGE_ENDPOINTTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace baxter_interface_msgs
{
template <class ContainerAllocator>
struct EndpointTarget_
{
  typedef EndpointTarget_<ContainerAllocator> Type;

  EndpointTarget_()
    : pose()
    , mode(0)  {
    }
  EndpointTarget_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_CARTESIAN)
  #undef MODE_CARTESIAN
#endif
#if defined(_WIN32) && defined(MODE_NORMAL)
  #undef MODE_NORMAL
#endif
#if defined(_WIN32) && defined(MODE_SKIP)
  #undef MODE_SKIP
#endif

  enum {
    MODE_CARTESIAN = 1u,
    MODE_NORMAL = 2u,
    MODE_SKIP = 3u,
  };


  typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> const> ConstPtr;

}; // struct EndpointTarget_

typedef ::baxter_interface_msgs::EndpointTarget_<std::allocator<void> > EndpointTarget;

typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTarget > EndpointTargetPtr;
typedef boost::shared_ptr< ::baxter_interface_msgs::EndpointTarget const> EndpointTargetConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator1> & lhs, const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator1> & lhs, const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baxter_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caa9a74dee2796f22565dda7cca89fd2";
  }

  static const char* value(const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcaa9a74dee2796f2ULL;
  static const uint64_t static_value2 = 0x2565dda7cca89fd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_interface_msgs/EndpointTarget";
  }

  static const char* value(const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "##limb pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"## motion mode\n"
"uint8 mode\n"
"uint8 MODE_CARTESIAN = 1\n"
"uint8 MODE_NORMAL = 2\n"
"uint8 MODE_SKIP = 3\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndpointTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_interface_msgs::EndpointTarget_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_INTERFACE_MSGS_MESSAGE_ENDPOINTTARGET_H
